version: '3.8'
services: 
  app1:
    build: ./app1
    image: martingtaylor/app1:latest
    container_name: app1
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
      DATABASE_URI: ${DATABASE_URI} 

  app2:
    build: ./app2
    image: martingtaylor/app2:latest
    container_name: app2
    ports:
    - target: 5002
      published: 5002
      protocol: tcp

  app3:
    build: ./app3
    image: martingtaylor/app3:latest
    container_name: app3
    ports:
    - target: 5003
      published: 5003
      protocol: tcp

  app4:
    build: ./app4
    image: martingtaylor/app4:latest
    container_name: app4
    ports:
    - target: 5004
      published: 5004
      protocol: tcp
