---
# tasks file for worker
- name: Add worker to swarm
  community.docker.docker_swarm:
    state: join
    join_token: "{{ hostvars['manager']['swarm_info']['swarm_facts']['JoinTokens']['Worker'] }}"
    remote_addrs: [ 'manager:2377' ]